### ISSUE TITLE
EXE file issue

### ISSUE THREAD

**Issue by FlippantDev** [Inplex-sys/BlackCap-Grabber-NoDualHook#35]
![image](https://github.com/Inplex-sys/BlackCap-Grabber-NoDualHook/assets/134905706/236e1cda-b497-4778-a116-488c3fd85563)
idk what happened when it was pyinstalling the thing but thats the error that shows

Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 60, in create_connection
  File "socket.py", line 963, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1092, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 210, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001D6E7DF2BD0>: Failed to resolve 'paste.bingner.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paste.bingner.com', port=443): Max retries exceeded with url: /paste/fhvyp/raw (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6E7DF2BD0>: Failed to resolve 'paste.bingner.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rubduck.py", line 104, in <module>
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paste.bingner.com', port=443): Max retries exceeded with url: /paste/fhvyp/raw (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D6E7DF2BD0>: Failed to resolve 'paste.bingner.com' ([Errno 11001] getaddrinfo failed)"))

**Comment by Inplex-sys** [comment]
check update
